# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\nstatistics\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"B\n\x11TaskStatsResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05views\x18\x02 \x01(\x05\x12\r\n\x05likes\x18\x03 \x01(\x05\"\"\n\x0fTopTasksRequest\x12\x0f\n\x07sort_by\x18\x01 \x01(\t\"2\n\x10TopTasksResponse\x12\x1e\n\x04task\x18\x01 \x03(\x0b\x32\x10.statistics.Task\"6\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"\x11\n\x0fTopUsersRequest\"2\n\x10TopUsersResponse\x12\x1e\n\x04user\x18\x01 \x03(\x0b\x32\x10.statistics.User\"*\n\x04User\x12\r\n\x05login\x18\x01 \x01(\t\x12\x13\n\x0btotal_likes\x18\x02 \x01(\x05\x32\xef\x01\n\x11StatisticsService\x12\x46\n\x0cGetTaskStats\x12\x17.statistics.TaskRequest\x1a\x1d.statistics.TaskStatsResponse\x12H\n\x0bGetTopTasks\x12\x1b.statistics.TopTasksRequest\x1a\x1c.statistics.TopTasksResponse\x12H\n\x0bGetTopUsers\x12\x1b.statistics.TopUsersRequest\x1a\x1c.statistics.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKREQUEST']._serialized_start=32
  _globals['_TASKREQUEST']._serialized_end=62
  _globals['_TASKSTATSRESPONSE']._serialized_start=64
  _globals['_TASKSTATSRESPONSE']._serialized_end=130
  _globals['_TOPTASKSREQUEST']._serialized_start=132
  _globals['_TOPTASKSREQUEST']._serialized_end=166
  _globals['_TOPTASKSRESPONSE']._serialized_start=168
  _globals['_TOPTASKSRESPONSE']._serialized_end=218
  _globals['_TASK']._serialized_start=220
  _globals['_TASK']._serialized_end=274
  _globals['_TOPUSERSREQUEST']._serialized_start=276
  _globals['_TOPUSERSREQUEST']._serialized_end=293
  _globals['_TOPUSERSRESPONSE']._serialized_start=295
  _globals['_TOPUSERSRESPONSE']._serialized_end=345
  _globals['_USER']._serialized_start=347
  _globals['_USER']._serialized_end=389
  _globals['_STATISTICSSERVICE']._serialized_start=392
  _globals['_STATISTICSSERVICE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
