# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"@\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"R\n\x11UpdateTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0f\n\x07updater\x18\x04 \x01(\t\"2\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\"%\n\x12\x44\x65leteTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x12GetTaskByIdRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"9\n\x0fGetTasksRequest\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"D\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t2\xa4\x02\n\x0bTaskService\x12\x33\n\nCreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x0b.tasks.Task\x12\x33\n\nUpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x0b.tasks.Task\x12\x41\n\nDeleteTask\x12\x18.tasks.DeleteTaskRequest\x1a\x19.tasks.DeleteTaskResponse\x12\x35\n\x0bGetTaskById\x12\x19.tasks.GetTaskByIdRequest\x1a\x0b.tasks.Task\x12\x31\n\x08GetTasks\x12\x16.tasks.GetTasksRequest\x1a\x0b.tasks.Task0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATETASKREQUEST']._serialized_start=22
  _globals['_CREATETASKREQUEST']._serialized_end=86
  _globals['_UPDATETASKREQUEST']._serialized_start=88
  _globals['_UPDATETASKREQUEST']._serialized_end=170
  _globals['_DELETETASKREQUEST']._serialized_start=172
  _globals['_DELETETASKREQUEST']._serialized_end=222
  _globals['_DELETETASKRESPONSE']._serialized_start=224
  _globals['_DELETETASKRESPONSE']._serialized_end=261
  _globals['_GETTASKBYIDREQUEST']._serialized_start=263
  _globals['_GETTASKBYIDREQUEST']._serialized_end=300
  _globals['_GETTASKSREQUEST']._serialized_start=302
  _globals['_GETTASKSREQUEST']._serialized_end=359
  _globals['_TASK']._serialized_start=361
  _globals['_TASK']._serialized_end=429
  _globals['_TASKSERVICE']._serialized_start=432
  _globals['_TASKSERVICE']._serialized_end=724
# @@protoc_insertion_point(module_scope)
