version: '3'
services:
  auth:
    depends_on:
      - db
    build: ./Auth
    restart: always
    ports:
      - "8080:8080"
    stop_signal: sigint
    command:
      - sh
      - -c
      - |
        poetry run python ./src/run.py
    networks:
      - mynetwork

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
